---

- name: Install Postgres
  yum:
    name: "{{ postgresql_packages }}"
    state: present
  become: True

- name: init postgresql (el-only)
  command: '{{ postgresql_initdb_command }}'
  args:
    creates: "{{ postgresql_conf_dir }}/PG_VERSION"
  become: True

- name: Make sure PostgreSQL is started
  service:
    name: '{{ postgresql_service_name }}'
    state: started
  register: postgresql_start
  become: True

- name: Wait for PostgreSQL to start if it wasnt
  wait_for:
    host: localhost
    port: 5432
  when: postgresql_start is changed
